# Generated by Django 4.0.3 on 2022-03-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'verbose_name': 'BackgroundImage', 'verbose_name_plural': 'BackgroundImage'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'services', 'verbose_name_plural': 'services'},
        ),
    ]
