# Generated by Django 4.0.3 on 2022-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
    ]
