# Generated by Django 4.0.3 on 2022-04-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
