# Generated by Django 4.0.3 on 2022-04-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_contact_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
