# Generated by Django 4.0.3 on 2022-03-30 10:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_backgroundimage_options_alter_services_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[app.models.validate_file_extension], verbose_name='Image'),
        ),
    ]
