# Generated by Django 4.0.3 on 2022-03-30 10:44

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_services_image_services_svg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='svg_file',
            field=models.FileField(blank=True, upload_to='assets/photos', validators=[app.validators.validate_file_extension]),
        ),
    ]
